name: fuse
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cached_network_image: ^2.3.1
  connectivity: ^0.4.9+2
  cupertino_icons: ^0.1.3
  http: ^0.12.2
  image_picker: ^0.6.7+7
  multi_image_picker: ^4.7.12
  provider: ^4.3.2+1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
